name: sketch_vision_app
description: A Sketch Vision App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0 # https://pub.dev/packages/collection
  equatable: ^2.0.2 # https://pub.dev/packages/equatable
  flutter_bloc: ^7.0.0 # https://pub.dev/packages/flutter_bloc
  ibm_apis: # https://github.com/mzdm/sketch_vision_app/tree/main/packages/ibm_apis
    path: packages/ibm_apis
  universal_platform: ^1.0.0-nullsafety # https://pub.dev/packages/universal_platform
  url_launcher: ^6.0.4 # https://pub.dev/packages/url_launcher

  # ui
  carbon_icons: ^0.0.1+2 # https://pub.dev/packages/carbon_icons
  crop_your_image: ^0.5.3 # https://pub.dev/packages/crop_your_image
  flex_color_picker: ^2.0.1 # https://pub.dev/packages/flex_color_picker
  fluent_ui: ^2.0.3 # https://pub.dev/packages/fluent_ui
  graphview: ^1.0.0-nullsafety.1 # https://pub.dev/packages/graphview
  shimmer: ^2.0.0 # https://pub.dev/packages/shimmer

  # desktop specific
  window_size: # https://github.com/google/flutter-desktop-embedding/tree/master/plugins/window_size
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: e48abe7c3e9ebfe0b81622167c5201d4e783bb81
  file_picker_cross: ^4.4.2 # https://pub.dev/packages/file_picker_cross
#  file_selector: ^0.8.2
#  file_selector_windows: ^0.0.2
#  file_selector_linux: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.3 # https://pub.dev/packages/mocktail
  bloc_test: ^8.0.1 # https://pub.dev/packages/bloc_test
  very_good_analysis: ^2.1.1 # https://pub.dev/packages/very_good_analysis

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
