name: ibm_apis
description: IBM Cloud APIs
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  built_value: ^8.0.6
  built_collection: ^5.0.0

dev_dependencies:
  built_value_generator: ^8.0.6
  build_runner: ^2.0.3